/*
Language: PowerOn
Author: Dylan Martinez <dylan@libum.io>
Category: Symitar, Jack Henry, Credit Union Platform
Description: Highlight.js grammar for Jack Henry PowerOn language
*/

export default function (hljs) {
  const regex = hljs.regex;
  const POWERON_IDENT_RE = '[a-zA-Z][a-zA-Z_0-9]*';
  const POWERON_IDENT_WORD_RE = '\\b' + POWERON_IDENT_RE + '\\b';

  const CONSTANTS_LIST =
    'LIVEINSTCHECK~PREVSYSTEMDATE~SYSACTUALDATE~SYSACTUALTIME~SYSCLIENTNUMBER~SYSCONSOLENUM~SYSHOSTNAME~SYSMEMOMODE~SYSSYMDIRECTORY~SYSTEMDATE~SYSUSERNUMBER~SYSWINDOWSLEVEL'.split(
      '~',
    );
  const DOCSTRING_LIST =
    'ABSTRACT~ACCESS~API~ATTRIBUTE~AUTHOR~BETA~CODE~CONFIG~COPYRIGHT~DEFAULT~DEFAULTVALUE~DEFINE~DEPRECATED~DESCRIPTION~ENUM~EXTERNAL~FILE~FILEOVERVIEW~GLOBAL~IGNORE~INTERNAL~LICENSE~MAIN~NAME~NAMESPACE~OVERRIDE~OVERVIEW~PARAM~PROP~PROPERTY~REQUIRE[DS]~SUMMARY~TODO~TUTORIAL~TYPE~VAR~VARIATION~VERSION~YIELDS~ARG~ARGUMENT~DESC~EXAMPLE'.split(
      '~',
    );
  const FUNCTIONS_LIST =
    'ABS~ANYSERVICE~ANYWARNING~CAPITALIZE~CHARACTERREAD~CHARACTERSEARCH~CHRVALUE~CODEREAD~COL~COPYAPP~CREATEFINANCEFROMCREDREP~CTRLCHR~DATASIZE~DATE~DATEOFFSET~DATEREAD~DATEVALUE~DAY~DAYOFWEEK~DIALOGINTROTEXT~DIALOGPROMPTCHAR~DIALOGPROMPTCODE~DIALOGPROMPTCOMBOOPTION~DIALOGPROMPTCOMBOSTART~DIALOGPROMPTDATE~DIALOGPROMPTLISTOPTION~DIALOGPROMPTLISTSTART~DIALOGPROMPTMONEY~DIALOGPROMPTNUMBER~DIALOGPROMPTPASSWORD~DIALOGPROMPTRATE~DIALOGPROMPTYESNO~DIALOGSTART~DIALOGSTARTGROUPBOX~DIALOGTEXTLISTOPTION~DIALOGTEXTLISTSTART~DIM~DIVPROJECTINIT~ELSE~EMAILLINE~EMAILSEND~EMAILSTART~ENTERCHARACTER~ENTERCODE~ENTERDATE~ENTERLINE~ENTERMONEY~ENTERNUMBER~ENTERRATE~ENTERYESNO~EXECUTE~EXP~FILEARCHIVEADD~FILEARCHIVEEXTRACT~FILECLOSE~FILECREATE~FILEDECRYPT~FILEDELETE~FILEENCRYPT~FILEGETPOS~FILELISTCLOSE~FILELISTOPEN~FILELISTREAD~FILEOPEN~FILEREAD~FILEREADLINE~FILESETPOS~FILEWRITE~FILEWRITELINE~FLOAT~FLOATVALUE~FLOOR~FORMAT~FTPCLOSE~FTPCMD~FTPGET~FTPLOGIN~FTPOPEN~FTPPUT~FULLYEAR~HOUR~HPBOXDRAW~HPFONT~HPLINEDRAW~HPLINESPERINCH~HPSETUP~HPUNDERLINE~HPXPOS~HPYPOS~HTMLVIEWLINE~HTMLVIEWOPEN~INITCREDITREPORT~INITSUBROUTINE~INT~LENGTH~LOANPROJECTINIT~LOG~LOWERCASE~MD5HASH~MINUTE~MOD~MONEY~MONEYREAD~MONTH~NUMBER~NUMBERREAD~OUTPUTCLOSE~OUTPUTOPEN~OUTPUTSWITCH~PASSWORDHASH~POPUPMESSAGE~PWR~QUEUECREDITREPORT~RATE~RATEREAD~REPEATCHR~SCREENXYPOS~SEGMENT~SYSUSERNAME~TERMINATE~UPPERCASE~VALIDATEFIELDSET~VALUE~WINDDECONNECT~WINDDEDISCONNECT~WINDDEEXECUTE~WINDDEPOKEDATA~WINDOWSSEND~WINMESSAGEFIELD~WINMESSAGESTART~YEAR~YESNOPROMPT~YESNOREAD~GETDATACHAR~GETDATACHARACTER~GETDATADATE~GETDATAMONEY~GETDATANUMBER~GETDATARATE~GETFIELDDATAMAX~GETFIELDDATATYPE~GETFIELDHELPFILE~GETFIELDMNEMONIC~GETFIELDNAME~GETFIELDNUMBER'.split(
      '~',
    );
  const FUNCTIONS_NO_PARAMS_LIST =
    'FMPERFORM~HEADER~HEADERS~HPESC~HPRESET~HTMLVIEWDISPLAY~PRINT~PULLCREDITREPORT~STOPBLINK~SUPPRESSNEWLINE~THEN~TOTAL~TRAILERS~TRANPERFORM~WHILELIMIT~WIDTH'.split(
      '~',
    );
  const NAMESPACES_LIST =
    'ACCOUNTCHANGE~ACS~APPLICATION~ATMDIALOG~AUDIO~AUDIOLOANAPP~BATCH~CARDCREATIONWIZARD~CERTIFICATE~CHECKDISBURSEDWIZARD~COLLECTION~CUSTOMFORMS~CUSTOMFORMSWINDOWS~DEMAND~EXCPITEM~HOMEBANKING~MCW~MCWINTERACTIVE~STATELESS~SUBROUTINE~SYMCONNECT~VALIDATION~WINDOWS~WINDOWSPRINT'.split(
      '~',
    );
  const KEYWORDS_LIST =
    'ACROSS~AFTERLAST~ALL~AND~ANY~APPEND~ARRAY~ASCII~BEFOREFIRST~BELL~BLINK~BLOCKSIZE~BRIGHT~CALL~CHANGE~CHARACTER~CLEARSERVICE~CLEARWARNING~CREATE~DATAFILE~DATE~DEFINE~DELETE~DIALOGCLOSE~DIALOGDISPLAY~DIALOGENDGROUPBOX~DIALOGENDGROUPING~DIALOGNEWCOLUMN~DIALOGPROMPTCOMBOEND~DIALOGPROMPTLISTEND~DIALOGSTARTGROUPING~DIALOGTEXTLISTEND~DIVPROJECTCALC~DO~EACH~EBCDIC~ELSE~END~ENTERDELIMITER~EVERY~FLOAT~FOR~FORMLENGTH~LABELS~LANDSCAPE~LASTACCOUNT~LASTCREATE~LASTSEQUENCE~LEFT~LETTER~LNINSFROMSH~LOC~LOANPROJECTCALC~MODIFY~MONEY~NEWLINE~NEWPAGE~NEXT~NEXTACCOUNT~NEXTCARD~NEXTCHECK~NEXTCOLLATERAL~NEXTCTR~NEXTDOCUMENT~NEXTMBRADDRESS~NEXTSEQUENCE~NEXTULI~NONANSISTANDARD~NONE~NOT~NUMBER~OR~OVERDRAWAVAILABLECALC~OVERDRAWAVAILABLEINIT~PORTRAIT~PREFIX~PRINT~PRINTCONTROL~PROCEDURE~RATE~READ~READWRITE~RECORDSIZE~REPORTCATEGORY~REVISE~REVLANDSCAPE~REVPORTRAIT~RIGHT~SAVEMODE~SELECT~SET~SETSERVICE~SETWARNING~SETUP~SORT~STARTING~SUBTOTAL~SUPPRESS~TARGET~TARGETFILE~TITLE~TOTAL~UNIQUEKEY~UNTIL~WHILE~WINMESSAGESEND~WINMODETEXT~WINMODEWINDOWS~WRAP~WRITE'.split(
      '~',
    );
  const OPERATORS_LIST = '\\+~\\-~\\*~\\/~\\=~<=~>=~<>~<~>~AND~OR~NOT'.split('~');
  const RECORD_LIST =
    'ACCOUNT~ACHADDENDA~ACHADDINFO~ACHEDIT~ACHITEM~ACTIVITY~AGREEMENT~AGREEMENT NOTE~AGREEMENT TRANSACTION~ATMDIALOG~BATCHACHORIG~BILL~CARD~CARD ACCESS~CARD NAME~CARD NOTE~CASHLETTER~CASHORDER~CDMDIALOG~CHECK~CHECK FMHISTORY~COLLATERAL~COLLATERAL COLLHOLD~COLLATERAL DOCUMENT~COLLATERAL DOCUMENT TRACKING~COLLATERAL FMHISTORY~COLLATERAL TRACKING~COMMENT~CORPTRANSFER~CPWORKCARD~CPWORKCARD NOTE~CPWORKCARD TRACKING~CREDREP~CREDREP ITEM~CTR~CTR FMHISTORY~CTR NOTE~CTRACCOUNT~CTRFOREIGN~CTRPERSON~DEALER~DEALER COMMENT~DEALER FMHISTORY~DEALER NOTE~DEALER TRACKING~EFT~EFT ADDENDAINFO~EFT NAME~EFT TRANSFER~EXCPADDENDA~EXCPADDINFO~EXCPITEM~EXTERNALACCOUNT~EXTERNALLOAN~EXTERNALLOAN NAME~EXTERNALLOAN NOTE~EXTERNALLOAN TRACKING~EXTERNALLOAN TRANSFER~FMHISTORY~GLACCOUNT~GLACCOUNT FMHISTORY~GLACCOUNT TRACKING~GLENTRY~GLHISTORY~GLSUBACCOUNT~GLTRAN~HOUSEHOLD~INVENTORY~INVOICE~INVOICE NOTE~IRA~IRS~IRS DISTRIBUTION~IRS NAME~LOAN~LOAN BANKRUPTCY~LOAN BANKRUPTCY PREPETITIONBAL~LOAN ESCROW~LOAN ESCROWANALYSIS~LOAN HOLD~LOAN LNSEGMENT~LOAN NAME~LOAN NOTE~LOAN PLEDGE~LOAN PLEDGE NAME~LOAN SCHEDULE~LOAN TRACKING~LOAN TRANSACTION~LOAN TRANSFER~LOANAPP~LOANAPP ESCROW~LOANAPP ESCROWANALYSIS~LOANAPP FINANCE~LOANAPP LNSEGMENT~LOANAPP NOTE~LOANAPP PERSON~LOANAPP PLEDGE~LOANAPP SCHEDULE~LOANAPP TRACKING~LOOKUP~MBRADDRESS~MBRADDRESS FMHISTORY~MEMBERREC~MEMBERREC FMHISTORY~NAME~NONACCTNAME~NONACCTNAME FMHISTORY~NOTE~PARTICIPANT~PARTICIPANT FMHISTORY~PARTICIPANT NOTE~PARTICIPANT TRANSACTION~PARTICIPATION~PARTICIPATION FMHISTORY~PARTICIPATION NOTE~PARTICIPATIONLOAN~PARTICIPATIONLOAN NOTE~PAYEE~PAYROLL~PLEDGE~POOL~POOLLOAN~PORTFOLIO~PORTFOLIO HOLD~PORTFOLIO NOTE~PORTFOLIO TRACKING~PREFERENCE~PREFERENCE ACCESS~RECEIVEDITEM~REMITTANCE~RESERVEPLAN~RESERVEPLAN LOAN~RESERVEPLAN TRACKING~RESERVEPLAN TRANSACTION~SAVINGS~SHARE~SHARE ANALYSIS~SHARE ANALYSISGROUP~SHARE ANALYSISPLAN~SHARE HOLD~SHARE NAME~SHARE NOTE~SHARE TRACKING~SHARE TRANSACTION~SHARE TRANSFER~SITE~SITE CASHORDERTYPE~TRACKING~USER~USER TRACKING~VENDOR~VENDOR FMHISTORY~WESTERNUNION~WESTERNUNION OFACDETAILS~WIRE~WIRE BENEFICIARYADV~WIRE BENEFICIARYFIADV~WIRE BENEFICIARYFIINFO~WIRE BENEFICIARYINFO~WIRE DRAWDOWNDEBITACCTADV~WIRE FITOFIINFO~WIRE FMHISTORY~WIRE INTERMEDFIADV~WIRE INTERMEDFIINFO~WIRE OFACDETAILS~WIRE RECEIVERFIINFO~WIRE SERVICEMESSAGE~WIRE USCAUDITINFO~WORKLISTEDIT~WORKLISTEDIT WORKLISTFIELD'.split(
      '~',
    );

  function noneOf(...list) {
    return regex.concat('(?!\\b(?:', list.join('|'), ')\\b)');
  }

  const COMMENTS = [
    hljs.COMMENT('\\[', ']', {
      relevance: 0,
      contains: [
        {
          match: regex.concat(/@/, regex.either(...DOCSTRING_LIST), /\b/),
          scope: 'doctag',
          relevance: 0,
        },
      ],
    }),
  ];

  const INCLUDE = {
    match: /#INCLUDE\b/,
    scope: 'keyword',
    relevance: 10,
  };

  const KEYWORDS = {
    $pattern: regex.concat(/(?<!:)\b/, POWERON_IDENT_WORD_RE, /\b/),
    keyword: [...KEYWORDS_LIST],
  };

  const NUMBERS = {
    match: /\b\d+(\.\d+)?\b/,
    scope: 'number',
    relevance: 0,
  };

  const OPERATORS = {
    match: regex.either(...OPERATORS_LIST),
    scope: 'operator',
    relevance: 0,
  };

  const PUNCTUATION = {
    match: /[\[\]\(\)\{\}:;,]/,
    scope: 'punctuation',
    relevance: 0,
  };

  const STRINGS = [hljs.APOS_STRING_MODE, hljs.QUOTE_STRING_MODE];

  const SYMITAR_NAMESPACES = [
    // Constants
    {
      match: regex.concat(/\b/, regex.either(...CONSTANTS_LIST), /\b/),
      scope: 'variable.constant',
      relevance: 1,
    },
    // Database records
    {
      match: regex.concat(/\b/, regex.either(...RECORD_LIST), /\b(?=\:|\s+)/),
      scope: 'built_in',
      relevance: 10,
    },
    // Functions
    {
      match: regex.concat(/\b/, regex.either(...FUNCTIONS_LIST), /(?=\()|\s+(?=\()/),
      scope: 'title.function',
      relevance: 1,
    },
    {
      match: regex.concat(/\b/, regex.either(...FUNCTIONS_NO_PARAMS_LIST), /\b/),
      scope: 'title.function',
      relevance: 1,
    },
    // Namespaces
    {
      match: regex.concat(/\b/, regex.either(...NAMESPACES_LIST), /\b/),
      scope: 'built_in',
      relevance: 10,
    },
    // Procedures
    {
      match: /(?<=(\bprocedure|call\b)\s+)\w+/,
      scope: 'title.function',
      relevance: 1,
    },
  ];

  const RESERVED_WORDS = [...CONSTANTS_LIST, ...KEYWORDS_LIST, ...NAMESPACES_LIST, ...RECORD_LIST];

  const VARIABLES = {
    match: [regex.concat(/\b/, noneOf(...RESERVED_WORDS), /\b/), POWERON_IDENT_RE],
    scope: { 2: 'variable' },
    relevance: 0,
  };

  const VARIABLES_AT = {
    match: '@' + POWERON_IDENT_RE,
    scope: 'variable',
    relevance: 1,
  };

  const VARIABLES_FIELD = {
    match: regex.concat(/(?<=:)\b/, POWERON_IDENT_RE, /\b/),
    scope: 'property',
    relevance: 0,
  };

  return {
    name: 'PowerOn',
    aliases: ['poweron'],
    case_insensitive: true,
    keywords: KEYWORDS,
    contains: [
      COMMENTS,
      INCLUDE,
      NUMBERS,
      OPERATORS,
      PUNCTUATION,
      ...STRINGS,
      SYMITAR_NAMESPACES,
      VARIABLES_FIELD,
      VARIABLES_AT,
      VARIABLES,
    ],
  };
}
