/**
 * Language: PowerOn
 * Author: Dylan Martinez <dylan@libum.io>
 * Category: Symitar, Jack Henry, Credit Union Platform
 * Description: Highlight.js grammar for Jack Henry PowerOn language
 */

export default function (hljs) {
  const regex = hljs.regex;
  const POWERON_IDENT_RE = '[a-zA-Z][a-zA-Z_0-9]*';
  const POWERON_IDENT_WORD_RE = '\\b' + POWERON_IDENT_RE + '\\b';

  const CONSTANTS_LIST = 'LIVEINSTCHECK|PREVSYSTEMDATE|SYSACTUALDATE|SYSACTUALTIME|SYSCLIENTNUMBER|SYSCONSOLENUM|SYSHOSTNAME|SYSMEMOMODE|SYSSYMDIRECTORY|SYSTEMDATE|SYSUSERNUMBER|SYSWINDOWSLEVEL'.split('|');
  const DOCSTRING_LIST = 'ABSTRACT|ACCESS|API|ATTRIBUTE|AUTHOR|BETA|CODE|CONFIG|COPYRIGHT|DEFAULT|DEFAULTVALUE|DEFINE|DEPRECATED|DESCRIPTION|ENUM|EXTERNAL|FILE|FILEOVERVIEW|GLOBAL|IGNORE|INTERNAL|LICENSE|MAIN|NAME|NAMESPACE|OVERRIDE|OVERVIEW|PARAM|PROP|PROPERTY|REQUIRE[DS]|SUMMARY|TODO|TUTORIAL|TYPE|VAR|VARIATION|VERSION|YIELDS|ARG|ARGUMENT|DESC|EXAMPLE'.split('|');
  const FUNCTIONS_LIST = 'CREATEFINANCEFROMCREDREP|DIALOGPROMPTCOMBOSTART|DIALOGPROMPTCOMBOOPTION|DIALOGPROMPTLISTSTART|DIALOGPROMPTLISTOPTION|DIALOGPROMPTNUMBER|DIALOGPROMPTMONEY|DIALOGPROMPTYESNO|DIALOGPROMPTRATE|DIALOGPROMPTPASSWORD|DIALOGPROMPTDATE|DIALOGSTARTGROUPBOX|DIALOGSTART|DIALOGTEXTLISTSTART|DIALOGTEXTLISTOPTION|DIVPROJECTINIT|LOANPROJECTINIT|EMAILSTART|EMAILSEND|EMAILLINE|FILEARCHIVEEXTRACT|FILEARCHIVEADD|FILECREATE|FILEENCRYPT|FILEDECRYPT|FILEDELETE|FILELISTOPEN|FILELISTCLOSE|FILELISTREAD|FILESETPOS|FILEWRITE|FILEWRITELINE|FILEGETPOS|FILECLOSE|FILEOPEN|FILEREAD|FILEREADLINE|FTPLOGIN|FTPOPEN|FTPGET|FTPCMD|FTPCLOSE|FTPPUT|FULLYEAR|GETFIELDDATATYPE|GETFIELDDATAMAX|GETFIELDHELPFILE|GETFIELDMNEMONIC|GETFIELDNAME|GETFIELDNUMBER|GETDATADATE|GETDATACHARACTER|GETDATAMONEY|GETDATANUMBER|GETDATARATE|GETDATACHAR|HPBOXDRAW|HPFONT|HPSETUP|HPUNDERLINE|HPLINEDRAW|HPLINESPERINCH|HPXPOS|HPYPOS|HTMLVIEWOPEN|HTMLVIEWLINE|INITCREDITREPORT|INITSUBROUTINE|LOG|CAPITALIZE|LOWERCASE|UPPERCASE|INT|MD5HASH|MINUTE|YEAR|EXP|MOD|FLOATVALUE|FLOAT|FLOOR|FORMAT|MONEYREAD|MONEY|MONTH|NUMBERREAD|NUMBER|OUTPUTCLOSE|OUTPUTOPEN|OUTPUTSWITCH|PASSWORDHASH|POPUPMESSAGE|PWR|QUEUECREDITREPORT|RATE|RATEREAD|REPEATCHR|SCREENXYPOS|SEGMENT|SYSUSERNAME|VALIDATEFIELDSET|VALUE|WINDDEEXECUTE|WINDDEPOKEDATA|WINDDECONNECT|WINDDEDISCONNTECT|WINDOWSSEND|WINMESSAGEFIELD|WINMESSAGESTART|YESNOPROMPT|YESNOREAD|COPYAPP|CHRVALUE'.split('|');
  const FUNCTIONS_NO_PARAMS_LIST = 'TRANPERFORM|FMPERFORM|WHILELIMIT|HEADER|HEADERS|HTMLVIEWDISPLAY|HPESC|HPRESET|WIDTH|STOPBLINK|SUPPRESSNEWLINE|PULLCREDITREPORT|TRAILERS'.split('|');
  const NAMESPACES_LIST = 'MCWINTERACTIVE|CARDCREATIONWIZARD|CHECKDISBURSEDWIZARD|WINDOWSPRINT|APPLICATION|HOMEBANKING|STATELESS|WINDOWS|SYMCONNECT|BATCH|CUSTOMFORMS|VALIDATION|DEMAND|COLLECTION|SUBROUTINE|AUDIOLOANAPP|AUDIO|MCW|ACS|CERTIFICATE|ACCOUNTCHANGE'.split('|');
  const KEYWORDS_LIST = 'ARRAY|CHRARRAY|CODE|CALL|COL|DATE|DEFINE|DIALOGSTARTGROUPING|DIALOGENDGROUPING|DIALOGCLOSE|DIALOGDISPLAY|DIALOGINTROTEXT|DIALOGNEWCOLUMN|DIALOGPROMPTCOMBOEND|DIALOGPROMPTLISTEND|DIALOGTEXTLISTEND|DIM|DIVPROJECTCALC|LOANPROJECTCALC|FMPERFORM|FORMLENGTH|HEADERS|HEADER|HTMLVIEWDISPLAY|HPESC|HPRESET|IF|LABELS|LEFT|LETTER|NEWLINE|NEWPAGE|NONANSISTANDARD|NONE|NUMBER|PRINT|PRINTCONTROL|PROCEDURE|PULLCREDITREPORT|RATE|RATECHANGE|RATECHANGES|REPORTCATEGORY|RIGHT|SELECT|SERVICEMESSAGE|SETUP|SORT|STARTING|SUBTOTAL|SUPPRESS|SUPPRESSNEWLINE|TARGET|TERMINATE|TITLE|TOTAL|TRAILERS|TRANPERFORM|VARARRAY|WHILE|WHILELIMIT|WIDTH|WINMESSAGESEND|WINMODETEXT|WINMODEWINDOWS|ACROSS|ALL|ANY|BELL|BLINK|BRIGHT|CHARACTER|DATAFILE|DO|EACH|ELSE|END|ENTERDELIMITER|ENTERLINE|EVERY|FLOAT|FOR|FORMLENGTH|THEN'.split('|');
  const OPERATORS_LIST = '\\+|\\-|\\*|\\/|\\=|<=|>=|<>|<|>|AND|OR|NOT'.split('|');
  const RECORD_LIST = 'RESERVEPLAN TRACKING|RESERVEPLAN LOAN|RESERVEPLAN TRANSACTION|RESERVEPLAN|DEALER TRACKING|DEALER COMMENT|DEALER NOTE|DEALER FMHISTORY|DEALER|LOANAPP TRACKING|LOANAPP SCHEDULE|LOANAPP LNSEGMENT|LOANAPP ESCROWANALYSIS|LOANAPP ESCROW|LOANAPP PLEDGE|LOANAPP NOTE|LOANAPP PERSON|LOANAPP FINANCE|LOANAPP|LOAN SCHEDULE|LOAN LNSEGMENT|LOAN ESCROWANALYSIS|LOAN ESCROW|LOAN PLEDGE NAME|LOAN PLEDGE|LOAN NOTE|LOAN NAME|LOAN TRANSACTION|LOAN HOLD|LOAN BANKRUPTCY PREPETITIONBAL|LOAN BANKRUPTCY|LOAN TRACKING|LOAN|RECEIVEDITEM|ATMDIALOG|ACHADDENDA|ACHITEM|ACHADDINFO|ACHEDIT|ACCOUNT CHANGE HISTORY TRACKING|ACCOUNT|AGREEMENT TRANSACTION|AGREEMENT NOTE|AGREEMENT|ACTIVITY|APPLICATION PLEDGE|APPLICATION FINANCE|APPLICATION PERSON|APPLICATION|ACCESS|ADDENDA|ADDITIONAL INFO|BATCHACHORIG|BILL|BLOCK RULE OVERRIDE TRACKING|CASHLETTER|CASHORDER|CARD ACCESS|CARD NAME|CARD NOTE|CARD|CASHORDERTYPE|COLLECTION TRACKING|COLLECTION WORKCARD|COLLATERAL DOCUMENT TRACKING|COLLATERAL DOCUMENT|COLLATERAL FMHISTORY|COLLATERAL COLLHOLD|COLLATERAL TRACKING|COLLATERAL|COMMENT|CORPTRANSFER|CORPORATE MEMBER DATA TRACKING|CREDIT CARD STATUS INQUIRY TRACKING|CREDIT REPORT ITEM|CREDIT REPORT|CTR NOTE|CTR ACCOUNT|CTR PERSON|CTR FOREIGN|CTR FMHISTORY|CTR|CHECK FMHISTORY|CHECK|CDMDIALOG|CPWORKCARD TRACKING|CPWORKCARD NOTE|CPWORKCARD|EXCPADDENDA|EXCPADDINFO|EXCPITEM|EXTERNALACCOUNT|EXTERNALLOAN TRACKING|EXTERNALLOAN NOTE|EXTERNALLOAN NAME|EXTERNALLOAN TRANSFER|EXTERNALLOAN|EFT ADDENDAINFO|EFT TRANSFER|EFT NAME|EFT|FACT ACT IDENTITY THEFT RED FLAG TRACKING|FICS STATUS INQUIRY TRACKING|FMHISTORY|FOREIGN COUNTRY ACCESS TRACKING|GL TRAN|GL HISTORY|GL ENTRY|GL SUBACCOUNT|GL ACCOUNT TRACKING|GL ACCOUNT FMHISTORY|GL ACCOUNT|HOUSEHOLD|HOLD|IRS DISTRIBUTION|IRS NAME|IRS|IRA|INVENTORY|INVOICE NOTE|INVOICE|LOOKUP|MEMBERREC FMHISTORY|MEMBERREC|MBRADDRESS FMHISTORY|MBRADDRESS|NAME|NETTELLER TRACKING|NONACCTNAME FMHISTORY|NONACCTNAME|NON-MBR BOND/MEMBER 1099-INT TRACKING|NOTE|PARTICIPATION TRANSACTION|PARTICIPATION LOAN NOTE|PARTICIPATION LOAN|PARTICIPATION FMHISTORY|PARTICIPATION|PAYEE|PLEDGE|PREFERENCE ACCESS|PREFERENCE|PORTFOLIO TRACKING|PORTFOLIO NOTE|PORTFOLIO HOLD|PORTFOLIO|POOLLOAN|POOL|REMITTANCE|SAVINGS|SERVICE LIST TRACKING|SHARE TRANSFER|SHARE TRANSACTION|SHARE NOTE|SHARE NAME|SHARE TRACKING|SHARE ANALYSISPLAN|SHARE ANALYSISGROUP|SHARE ANALYSIS|SHARE HOLD|SHARE|SITE CASHORDERTYPE|SITE|TRACKING|TRANSACTION|UNCLAIMED PROPERTY INFORMATION TRACKING|USER TRACKING|USER|WESTERNUNION OFACDETAILS|WESTERNUNION|WIRE USC AUDIT INFO|WIRE SERVICE MESSAGE|WIRE RECEIVERFIINFO|WIRE OFACDETAILS|WIRE INTERMEDFIINFO|WIRE INTERMEDFIADV|WIRE FITOFIINFO|WIRE DRAWDOWNDEBITACCTADV|WIRE BENEFICIARYINFO|WIRE BENEFICIARYFIINFO|WIRE BENEFICIARYFIADV|WIRE BENEFICIARYADV|WIRE FMHISTORY|WIRE|WORKLISTEDIT WORKLISTFIELD|WORKLISTEDIT'.split('|');

  function noneOf(...list) {
    return regex.concat('(?!', list.join('|'), ')');
  }

  const COMMENTS = [
    hljs.COMMENT('\\[', ']', {
      relevance: 0,
      contains: [
        {
          match: regex.concat(/@/, regex.either(...DOCSTRING_LIST), /\b/),
          scope: 'doctag',
          relevance: 0
        }
      ]
    })
  ];

  const INCLUDE = {
    match: /#INCLUDE\b/,
    scope: 'keyword',
    relevance: 0
  }

  const KEYWORDS = {
    $pattern: regex.concat(/(?<!:)\b/, POWERON_IDENT_WORD_RE, /\b/),
    keyword: [...KEYWORDS_LIST],
  };

  const NUMBERS = {
    match: /\b\d+(\.\d+)?\b/,
    scope: 'number',
    relevance: 0
  }

  const OPERATORS = {
    match: regex.either(...OPERATORS_LIST),
    scope: 'operator',
    relevance: 0
  };

  const PUNCTUATION = {
    match: /[\[\]\(\)\{\}:;,]/,
    scope: 'punctuation',
    relevance: 0
  }

  const STRINGS = [
    hljs.APOS_STRING_MODE,
    hljs.QUOTE_STRING_MODE
  ];

  const SYMITAR_NAMESPACES = [
    // Constants
    {
      match: regex.concat(/\b/, regex.either(...CONSTANTS_LIST), /\b/),
      scope: 'variable.constant',
      relevance: 0
    },
    // Database records
    {
      match: regex.concat(/\b/, regex.either(...RECORD_LIST), /\b(?=\:|\s+)/),
      scope: 'built_in',
      relevance: 0
    },
    // Functions
    {
      match: regex.concat(/\b/, regex.either(...FUNCTIONS_LIST), /(?=\()|\s+(?=\()/),
      scope: 'title.function',
      relevance: 0,
    },
    {
      match: regex.concat(/\b/, regex.either(...FUNCTIONS_NO_PARAMS_LIST), /\b/),
      scope: 'title.function',
      relevance: 0
    },
    // Namespaces
    {
      match: regex.concat(/\b/, regex.either(...NAMESPACES_LIST), /\b/),
      scope: 'built_in',
      relevance: 0
    },
    // Procedures
    {
      match: /(?<=(\bprocedure|call\b)\s+)\w+/,
      scope: 'title.function',
      relevance: 0
    }
  ];

  const RESERVED_WORDS = [
    ...CONSTANTS_LIST,
    ...KEYWORDS_LIST,
    ...NAMESPACES_LIST,
    ...RECORD_LIST
  ];

  const VARIABLES = {
    match: [
      regex.concat(/\b/, noneOf(...RESERVED_WORDS)),
      POWERON_IDENT_RE
    ],
    scope: { 2: 'variable' },
    relevance: 0
  };

  const VARIABLES_AT = {
    match: '@' + POWERON_IDENT_RE,
    scope: 'variable',
    relevance: 0
  };

  const VARIABLES_FIELD = {
    match: regex.concat(/(?<=:)\b/, POWERON_IDENT_RE, /\b/),
    scope: 'property',
    relevance: 0
  };

  return {
    name: 'PowerOn',
    aliases: ['poweron'],
    case_insensitive: true,
    keywords: KEYWORDS,
    contains: [
      COMMENTS,
      INCLUDE,
      NUMBERS,
      OPERATORS,
      PUNCTUATION,
      ...STRINGS,
      SYMITAR_NAMESPACES,
      VARIABLES_FIELD,
      VARIABLES_AT,
      VARIABLES
    ]
  }
}
